Added fixed point theorems section to main.tex
nabw/IMT3130 pull request #7
Opened 2024-11-10 14:39 UTC by SebastianFerra

2024-11-10 20:18 UTC, nabw requested changes
Gracias Seba. En clases vimos también el ejemplo del seno pero con Banach, por si lo puedes agregar por favor.

El resto todo ok, solo correcciones menores.

2024-11-10 20:18 UTC, nabw commented on Fixed_point.tex
> +using that $|\sin (x)|\leq 1$. This implies that $u_h$ is contained in a finite-dimensional ball $\mathcal{B}(0,r), r=C_2$. So $T_h:\mathcal{B}(0,r)\to \mathcal{B}(0,r)$ has at least one fixed point
Qué es BDD?

2024-11-10 20:18 UTC, nabw commented on Fixed_point.tex
> +From the previous result we can extend to $h\to 0$ through compactness. This can be generalized to another fixed point theorem as Schauder. It has 2 forms.
As Schauder - > known as Schauder's fixed point thm

2024-11-28 19:37 UTC, SebastianFerra commented
Ya actualicé los cambios en mi rama del fork pero no se si se acualizan solos para esta pull request :s

2024-11-28 19:47 UTC, nabw commented
Todo ok, Gracias!

2024-11-28 19:47 UTC, merged